# Generated by Django 4.0 on 2022-01-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articlescope_article_scope_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Раздел'},
        ),
    ]
