# Generated by Django 4.0 on 2022-01-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={},
        ),
        migrations.RemoveField(
            model_name='scope',
            name='articles',
        ),
    ]
