# Generated by Django 4.0 on 2022-01-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_scope_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='tag',
            field=models.TextField(default=22, verbose_name='Тег'),
            preserve_default=False,
        ),
    ]
