# Generated by Django 4.0 on 2023-02-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_articlescope_options_alter_scope_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['-main_tag', 'scope'], 'verbose_name': 'Тематика статей', 'verbose_name_plural': 'Тематики статьи'},
        ),
    ]
