# Generated by Django 4.0 on 2023-02-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_articlescope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['is_main', 'scope'], 'verbose_name': 'Тематика статей', 'verbose_name_plural': 'Тематики статьи'},
        ),
        migrations.RenameField(
            model_name='articlescope',
            old_name='main_tag',
            new_name='is_main',
        ),
    ]
