# Generated by Django 4.0 on 2023-02-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_scope_article_alter_scope_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main', 'tag'], 'verbose_name': 'Тематика статей', 'verbose_name_plural': 'Тематики статьи'},
        ),
    ]
